-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "endAt" TIMESTAMP(3),
ADD COLUMN     "owner" JSONB,
ADD COLUMN     "priority" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "position" SET DEFAULT 1,
ALTER COLUMN "assigned" DROP NOT NULL,
ALTER COLUMN "sprint" SET DEFAULT 2;
