import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/helper/provider";
import { Poppins } from 'next/font/google'

export const metadata: Metadata = {
  title: "Beeheal",
  description: "Generated by create next app",
};

const inter = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}
